#ifndef KPPQTCOMMONLIB_GLOBAL_H
#define KPPQTCOMMONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KPPQTCOMMONLIB_LIBRARY)
#  define KPPQTCOMMONLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define KPPQTCOMMONLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KPPQTCOMMONLIB_GLOBAL_H
